image: gcc
variables:
  GIT_STRATEGY: clone

build:ubuntu:32:
  tags:
    - "ubuntu"
    - "32"
  stage: build
  before_script:
     - whoami
     - sudo apt-get install -y cmake libopencv-dev libcv-dev libhighgui-dev pngcheck valgrind
  script:
    - mkdir build
    - cd build
    - cmake .. -DMOCK_SPECTROMETER=ON -DMOCK_SPECTROMETER_SHUTTER=ON -DMOCK_WEBCAM=ON -DMOCK_CAMERA=ON -DMOCK_FILTERWHEEL=ON
    - cmake --build .
    - ctest --output-on-failure .

build:ubuntu:64:
  tags:
    - "ubuntu"
    - "64"
  stage: build
  before_script:
     - whoami
     - sudo apt-get install -y cmake libopencv-dev libcv-dev libhighgui-dev pngcheck valgrind
  script:
    - mkdir build
    - cd build
    - cmake .. -DMOCK_SPECTROMETER=ON -DMOCK_SPECTROMETER_SHUTTER=ON -DMOCK_WEBCAM=ON -DMOCK_CAMERA=ON -DMOCK_FILTERWHEEL=ON
    - cmake --build .
    - ctest --output-on-failure .
