shallow_clone: false
clone_depth: 1
clone_folder: c:\dev\so2-camera
# to add several platforms to build matrix:
platform:
  - x64
install:
  - cmd: choco install -y OpenCV
before_build:
  - cmd: SET ARCH=x64
  - cmd: SET APP_PATH=%CD%
  - cmd: IF EXIST C:\OpenCV* CD C:\OpenCV*
  - cmd: SET OPENCV_ROOT_PATH=%CD%\opencv
  - cmd: SETX OPENCV_ROOT_PATH %OPENCV_ROOT_PATH%
  - cmd: CD %APP_PATH%
  - cmd: SET OPENCV_DIR=%OPENCV_ROOT_PATH%\build\%ARCH%\vc12\bin
  - cmd: SETX OPENCV_DIR %OPENCV_DIR%
  - cmd: SET PATH=%OPENCV_DIR%;%PATH%
build_script:
  - cd c:\dev\so2-camera
  - git submodule update --init --recursive
  - set
  - cmake -DMOCK_LOG=ON -Dmock=camera .
  - dir
  - msbuild ALL_BUILD.vcxproj /p:Configuration=Debug /p:Platform="Any CPU"
  - dir
  - dir Debug
  - tree
  - ctest -VV -C "Debug"
  - cmake -DMOCK_LOG=ON -Dmock=camera --build . --target RUN_TESTS --config debug
