install:
  - cinst OpenCV
  - set PATH=%PATH%;c:\OpenCV249\opencv\build\x86\vc11\bin
  - curl -L http://prdownloads.sourceforge.net/png-mng/pngcheck-2.3.0-win32.zip -o pngcheck.zip
  - unzip pngcheck.zip
  - copy pngcheck.exe src\io
os: unstable
build_script:
  - git submodule update --init
  - cmake -DCMAKE_BUILD_TYPE=Release -Dmock=camera -DMOCK_LOG=ON -DOpenCV_DIR=c:\OpenCV249\opencv\build .
  - cmake --build . --config Release
  - ctest --output-on-failure
